const allLists = (
  state = {
    primitives: [
      "Website",
      "NFT",
      "Classes",
      "Objects",
      "Variables",
      "Wallet",
      "Royalties",
      "RFID",
    ],
    nft: [
      "QR code",
      "Github",
      "Physical items (claymates vibe)",
      "Royalties",
      "Arweave",
      "Address",
      "Utility",
      "Aped",
      "exclusivity",
      "One of One",
      "Airdrops",
      "Digital functionality",
      "IRL",
      "Deflationary",
      "Burn",
      "Permanence",
      "Data NFT",
      "wagmi",
      "Passive income",
      "Art",
      "Rarity",
      "Fomo",
      "Secondary market",
      "Floor price",
      "Ticket to ride",
      "Smart contract",
      "Opensea",
      "Mint",
      "PFP",
      "Discord",
      "Vending machine",
      "community",
      "Whale",
      "Generative",
      "Limited mint",
      "Shilling",
      "IPFS",
      "Roadmap",
      "Proof of ownership",
    ],
    blockchain: [
      "Token",
      "Polkadot",
      "nodes",
      "Altcoin",
      "Debit card",
      "Uniswap",
      "encryption",
      "Lending",
      "Private key",
      "Stake",
      "Smart contracts",
      "rewards",
      "cardano",
      "Hardware wallet",
      "Store of value",
      "proof of stake",
      "Supply chain",
      "Miners",
      "Decentralized",
      "ATM",
      "Singularity net AI",
      "Governance",
      "Peer to peer",
      "NFT game",
      "Proof of work",
      "Oracle",
      "token",
      "Paper wallet",
      "Decentralized exchange",
      "Interoperability",
      "Stake pools",
      "Liquidity",
      "Stable coin",
      "Borrowing",
      "NFTs",
      "Defi",
      "Rarible",
      "Layer 2 solution",
      "Bitcoin",
      "wallets",
      "BAT",
      "Gas",
      "Exhange",
      "Digital identity",
      "Security",
      "Ledger",
      "VeChain",
    ],
    industry: [
      "Investing",
      "Pollination",
      "Toys",
      "Agriculture",
      "Marijuana",
      "IP Security",
      "Food Preservation",
      "Healthcare",
      "Recreational Sports",
      "Banking",
      "Financial services",
      "Food Preparation",
      "Transportation",
      "Wellness",
      "Dogs",
      "Virtual Reality",
      "Real estate",
      "Workout",
      "IP Discovery",
      "Fashion",
      "Automotive",
      "Communications",
      "Manufacturing",
      "Electricity",
      "Home Improvement",
      "Architecture",
      "Accounting/finance",
      "Housecleaning",
      " Food",
      "Tobacco",
      "Intoxicants",
      "Sports",
      "Renewables",
      "Porn",
      "Defense",
      "Alcohol",
      "Power/utilities",
      "Thinning hair/Male Pattern Baldness",
      "Beer",
      "Livestock",
      "Pharmaceuticals",
      "Biopharmaceuticals",
      "Infrastructure",
      "Music",
      "Home Workout Equipment",
      "Public resource",
      "products ",
      "Babies",
      "Technology",
      "Spa",
      "Organization/Planning",
      "Aerospace",
      "TV+entertainment",
      "Cryptocurrency",
      "Public health",
      "Education",
      "Textiles",
      "Public Safety",
      "Social Media",
      "Surgery",
      "Concerts/live performances",
      "Hunting/Fishing",
      "Beverages",
      "Self-Help",
      "blockchains",
    ],
    embody: [
      "Recreational Drugs",
      "Mobile App",
      "kid",
      "Web App",
      "Microbes",
      "Fortune 500",
      "TRIZ progression",
      "Fasteners",
      "Saving babies",
      "Ultrasonic",
      "Nanotechnology",
      "Seamless integration",
      "Social Media Platform",
      "Blockchain",
      "Virtual Reality",
      "IOT",
      "A system/means for organization",
      "Sportswear",
      "Liquid",
      "Flagship",
      "Automation",
      "Sensor-Monitor-Device (medium)",
      "After Automation",
      "Plastic Part",
      "Delivery Methods",
      "Plastic Part",
      "Stepper Motors",
      "Automation",
      "Healthcare",
      "Machine Learning",
      "Ebook",
      "Paper",
      "Vibration",
      "SaaS",
      "Service",
      "A process improvement",
      "Paint",
      "Batteries",
      "IOT",
      "IP Discovery",
      "Silicone",
      "Nourishment",
      "AI",
      "Consulting",
      "Biomimicry",
      "Houseplants",
      "Combine two existing innovations",
      "Proprietary Blend(s)",
    ],
    idZone: [
      "Research Tools",
      "Blockchain",
      "Ease of Use",
      "Genetics",
      "Quality Control",
      "Battery Life",
      "Cooling",
      "Time Reduction",
      "Batteries",
      "Poop",
      "Ethics/Morality",
      "Tools for Experts",
      "Efficiency",
      "Process Improvement",
      "Eliminating waste ",
      "Customer Experience",
      "Risk Reduction",
      "Speed of Use",
      "Research Workflow",
      "Drone",
      "IP Discovery",
      "Seamless integration",
      "Unicorn Idea(novel)",
      "Safety",
      "Energy efficiency",
      "Video",
      "Access ",
      "workplace security",
      "Payroll",
      "LEAN",
      "Pain",
      "Sterilization",
      "Surgery",
      "Quality Assurance",
      "Supply Chain",
      "Dispensing",
      "Lab Sterilization",
      "Patient Care ",
      "Microbes ",
      "Design",
      "Audio ",
      "Cost Reduction",
      "Grooming",
      "Public resource",
      "Heating",
      "UX",
      "frustration reduction",
      "Resource efficiency",
    ],
    companies: [
      "Uber",
      "Google",
      "Apple",
      "Grubhub",
      "AirBnB",
      "Alibaba",
      "Tesla",
      "Ikea",
      "Coca Cola",
      "Wikipedia",
      "Expedia",
      "Boeing",
      "Nasa",
      "Zara",
      "Skillshare",
      "Subscription box",
      "Instagram",
      "Reddit",
      "Google drive",
      "OneNote",
      "Walmart",
      "Starbucks",
      "Costco",
      "Spotify",
      "Youtube",
      "Coinbase",
      "Lockheed Martin",
      "Nike",
      "Gucci",
      "Shopify ",
      "Tesla",
      "Bitcoin",
      "Cryptocurrency",
      "AT&T",
      "Photoshop",
      "Autodesk",
      "Adobe",
      "Square",
      "Ebay",
      "Social Media",
      "SaaS",
      "Petco",
      "Etsy",
      "Berkshire Hathaway",
      "Ford",
      "Microsoft",
      "Procter and Gamble",
      "FedEx",
      "Disney",
      "Pfizer",
      "3M",
      "Dollar Tree",
      "SalesForce",
      "Notion",
      "Figma",
      "Uniswap",
      "ProductHunt",
      "PayPal",
      "McDonalds",
      "Southwest Airlines",
      "Wayfair",
      "Fox",
      "Meta",
      "Amazon",
      "Epic Games",
      "Twitter",
      "Discord",
      "WeWork",
      "DoorDash",
      "Tinder",
      "Instacart",
      "Dropbox",
      "Pinterest",
      "Zoom",
      "Craigslist",
      "TikTok",
      "WhatsApp",
      "Snapchat",
      "Roblox",
      "Twitch",
      "Amazon Prime",
      "Soundcloud",
      "Aliexpress",
      "Dominos",
      "Duolingo",
      "Calm",
      "Venmo",
      "Binance",
    ],
  },
  action
) => {
  switch (action.type) {
    case "LISTS":
      return state;

    default:
      return state;
  }
};

export default allLists;
