export const ThoughtRoute = [
  {
    urlHash: "Start",
    heading: "Start",
    text: "This is the start of the devlab",
    subtext: "This is the start of the devlab",
    buttonText: "Back",
    buttonText2: "Next",
    popupText: "This is the start of the devlab",
    placeholder: "This is the start of the devlab",
  },
  {
    urlHash: "Start2",
    heading: "Page 2",
    text: "This is the second page of the devlab",
    subtext: "This is the second page of the devlab",
    buttonText: "Back",
    buttonText2: "Next",
    popupText: "This is the second page of the devlab",
    placeholder: "This is the second page of the devlab",
  },
  {
    urlHash: "Start3",
    heading: "Page 3",
    text: "This is the third page of the devlab",
    subtext: "This is the third page of the devlab",
    buttonText: "Back",
    buttonText2: "Next",
    popupText: "This is the third page of the devlab",
    placeholder: "This is the third page of the devlab",
  },
];
